            package p000;
            
            public enum lIIi1il implements il01ioolo {
                NO_ERROR(0),
                INCOMPATIBLE_INPUT(1),
                INCOMPATIBLE_OUTPUT(2),
                INCOMPATIBLE_TFLITE_VERSION(3),
                MISSING_OP(4),
                DATA_TYPE_ERROR(6),
                CODE_SCANNER_PIPELINE_INFERENCE_ERROR(7),
                TFLITE_UNKNOWN_ERROR(8),
                MEDIAPIPE_ERROR(9),
                TIME_OUT_FETCHING_MODEL_METADATA(5),
                MODEL_NOT_DOWNLOADED(100),
                URI_EXPIRED(101),
                NO_NETWORK_CONNECTION(102),
                METERED_NETWORK(103),
                DOWNLOAD_FAILED(104),
                CODE_SCANNER_PIPELINE_INFERENCE_ERROR(105),
                CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(106),
                CODE_SCANNER_PIPELINE_INFERENCE_ERROR(107),
                CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(108),
                CODE_SCANNER_PIPELINE_INFERENCE_ERROR(109),
                CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(110),
                CODE_SCANNER_PIPELINE_INFERENCE_ERROR(111),
                CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(112),
                CODE_SCANNER_PIPELINE_INFERENCE_ERROR(113),
                CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(114),
                CODE_SCANNER_PIPELINE_INFERENCE_ERROR(115),
                CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(116),
                OPTIONAL_MODULE_NOT_AVAILABLE(201),
                OPTIONAL_MODULE_INIT_ERROR(202),
                CODE_SCANNER_PIPELINE_INFERENCE_ERROR(203),
                CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(204),
                CODE_SCANNER_PIPELINE_INFERENCE_ERROR(205),
                CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(206),
                CODE_SCANNER_PIPELINE_INFERENCE_ERROR(207),
                CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(301),
                CODE_SCANNER_PIPELINE_INFERENCE_ERROR(302),
                CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(303),
                CODE_SCANNER_PIPELINE_INFERENCE_ERROR(304),
                CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(305),
                CODE_SCANNER_PIPELINE_INFERENCE_ERROR(400),
                CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(401),
                CODE_SCANNER_PIPELINE_INFERENCE_ERROR(402),
                CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(403),
                CODE_SCANNER_PIPELINE_INFERENCE_ERROR(404),
                CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(405),
                CODE_SCANNER_PIPELINE_INFERENCE_ERROR(406),
                CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(407),
                UNKNOWN_ERROR(9999);

                public final int I00iOIl;

                lIIi1il(int i) {
/* 4 */             this.I00iOIl = i;
                }

                @Override
                public final int zza() {
/* 1 */             return this.I00iOIl;
                }
            }
