            package p000;

            import android.R;
            
            public abstract class OOilOii0o1I {
                public static final int[] I00000oIO = {R.attr.maxWidth, R.attr.maxHeight, R.attr.elevation, com.box.gallery.R.attr.backgroundTint, com.box.gallery.R.attr.behavior_draggable, com.box.gallery.R.attr.behavior_draggableOnNestedScroll, com.box.gallery.R.attr.behavior_expandedOffset, com.box.gallery.R.attr.behavior_fitToContents, com.box.gallery.R.attr.behavior_halfExpandedRatio, com.box.gallery.R.attr.behavior_hideable, com.box.gallery.R.attr.behavior_peekHeight, com.box.gallery.R.attr.behavior_saveFlags, com.box.gallery.R.attr.behavior_significantVelocityThreshold, com.box.gallery.R.attr.behavior_skipCollapsed, com.box.gallery.R.attr.gestureInsetBottomIgnored, com.box.gallery.R.attr.marginLeftSystemWindowInsets, com.box.gallery.R.attr.marginRightSystemWindowInsets, com.box.gallery.R.attr.marginTopSystemWindowInsets, com.box.gallery.R.attr.paddingBottomSystemWindowInsets, com.box.gallery.R.attr.paddingLeftSystemWindowInsets, com.box.gallery.R.attr.paddingRightSystemWindowInsets, com.box.gallery.R.attr.paddingTopSystemWindowInsets, com.box.gallery.R.attr.shapeAppearance, com.box.gallery.R.attr.shapeAppearanceOverlay, com.box.gallery.R.attr.shouldRemoveExpandedCorners};
                public static final int[] I00000oOI = {com.box.gallery.R.attr.carousel_alignment, com.box.gallery.R.attr.carousel_backwardTransition, com.box.gallery.R.attr.carousel_emptyViewsBehavior, com.box.gallery.R.attr.carousel_firstView, com.box.gallery.R.attr.carousel_forwardTransition, com.box.gallery.R.attr.carousel_infinite, com.box.gallery.R.attr.carousel_nextState, com.box.gallery.R.attr.carousel_previousState, com.box.gallery.R.attr.carousel_touchUpMode, com.box.gallery.R.attr.carousel_touchUp_dampeningFactor, com.box.gallery.R.attr.carousel_touchUp_velocityThreshold};
                public static final int[] I0000Il00O = {com.box.gallery.R.attr.behavior_autoHide, com.box.gallery.R.attr.behavior_autoShrink};
                public static final int[] I0000O = {com.box.gallery.R.attr.behavior_autoHide};
                public static final int[] I0000oI00 = {R.attr.inputType, R.attr.popupElevation, com.box.gallery.R.attr.dropDownBackgroundTint, com.box.gallery.R.attr.simpleItemLayout, com.box.gallery.R.attr.simpleItemSelectedColor, com.box.gallery.R.attr.simpleItemSelectedRippleColor, com.box.gallery.R.attr.simpleItems};
                public static final int[] I0001Ioi1lo = {R.attr.background, R.attr.checked, R.attr.insetLeft, R.attr.insetRight, R.attr.insetTop, R.attr.insetBottom, R.attr.checkable, com.box.gallery.R.attr.backgroundTint, com.box.gallery.R.attr.backgroundTintMode, com.box.gallery.R.attr.cornerRadius, com.box.gallery.R.attr.elevation, com.box.gallery.R.attr.icon, com.box.gallery.R.attr.iconGravity, com.box.gallery.R.attr.iconPadding, com.box.gallery.R.attr.iconSize, com.box.gallery.R.attr.iconTint, com.box.gallery.R.attr.iconTintMode, com.box.gallery.R.attr.opticalCenterEnabled, com.box.gallery.R.attr.rippleColor, com.box.gallery.R.attr.shapeAppearance, com.box.gallery.R.attr.shapeAppearanceOverlay, com.box.gallery.R.attr.strokeColor, com.box.gallery.R.attr.strokeWidth, com.box.gallery.R.attr.toggleCheckedStateOnClick};
                public static final int[] I000II = {R.attr.button, com.box.gallery.R.attr.buttonCompat, com.box.gallery.R.attr.buttonIcon, com.box.gallery.R.attr.buttonIconTint, com.box.gallery.R.attr.buttonIconTintMode, com.box.gallery.R.attr.buttonTint, com.box.gallery.R.attr.centerIfNoTextEnabled, com.box.gallery.R.attr.checkedState, com.box.gallery.R.attr.errorAccessibilityLabel, com.box.gallery.R.attr.errorShown, com.box.gallery.R.attr.useMaterialThemeColors};
                public static final int[] I000O01llI0 = {com.box.gallery.R.attr.buttonTint, com.box.gallery.R.attr.useMaterialThemeColors};
                public static final int[] I000OOo1O = {com.box.gallery.R.attr.shapeAppearance, com.box.gallery.R.attr.shapeAppearanceOverlay};
                public static final int[] I000OiO = {com.box.gallery.R.attr.damping, com.box.gallery.R.attr.stiffness};
                public static final int[] I000iOII = {R.attr.letterSpacing, R.attr.fontVariationSettings, R.attr.lineHeight, com.box.gallery.R.attr.fontVariationSettings, com.box.gallery.R.attr.lineHeight};
                public static final int[] I000l1 = {R.attr.textAppearance, R.attr.lineHeight, com.box.gallery.R.attr.lineHeight};
                public static final int[] I000lI = {com.box.gallery.R.attr.behavior_overlapTop};
                public static final int[] I000o00OoI0I = {com.box.gallery.R.attr.cornerFamily, com.box.gallery.R.attr.cornerFamilyBottomLeft, com.box.gallery.R.attr.cornerFamilyBottomRight, com.box.gallery.R.attr.cornerFamilyTopLeft, com.box.gallery.R.attr.cornerFamilyTopRight, com.box.gallery.R.attr.cornerSize, com.box.gallery.R.attr.cornerSizeBottomLeft, com.box.gallery.R.attr.cornerSizeBottomRight, com.box.gallery.R.attr.cornerSizeTopLeft, com.box.gallery.R.attr.cornerSizeTopRight};
                public static final int[] I000oI1ioi = {R.attr.maxWidth, R.attr.maxHeight, R.attr.elevation, com.box.gallery.R.attr.backgroundTint, com.box.gallery.R.attr.behavior_draggable, com.box.gallery.R.attr.coplanarSiblingViewId, com.box.gallery.R.attr.shapeAppearance, com.box.gallery.R.attr.shapeAppearanceOverlay};
                public static final int[] I00100l0 = {R.attr.textAppearance, com.box.gallery.R.attr.enforceMaterialTheme, com.box.gallery.R.attr.enforceTextAppearance};
            }
