            package com.google.android.gms.internal.mlkit_genai_speech;

            import com.google.mlkit.genai.common.GenAiException;
            
            public enum zzxp implements zzjy {
                NO_ERROR(0),
                INCOMPATIBLE_INPUT(1),
                INCOMPATIBLE_OUTPUT(2),
                INCOMPATIBLE_TFLITE_VERSION(3),
                MISSING_OP(4),
                DATA_TYPE_ERROR(6),
                TFLITE_INTERNAL_ERROR(7),
                TFLITE_UNKNOWN_ERROR(8),
                MEDIAPIPE_ERROR(9),
                TIME_OUT_FETCHING_MODEL_METADATA(5),
                MODEL_NOT_DOWNLOADED(100),
                URI_EXPIRED(101),
                NO_NETWORK_CONNECTION(102),
                METERED_NETWORK(103),
                DOWNLOAD_FAILED(104),
                MODEL_INFO_DOWNLOAD_UNSUCCESSFUL_HTTP_STATUS(105),
                MODEL_INFO_DOWNLOAD_NO_HASH(106),
                MODEL_INFO_DOWNLOAD_CONNECTION_FAILED(107),
                NO_VALID_MODEL(108),
                LOCAL_MODEL_INVALID(109),
                REMOTE_MODEL_INVALID(110),
                REMOTE_MODEL_LOADER_ERROR(111),
                REMOTE_MODEL_LOADER_LOADS_NO_MODEL(112),
                SMART_REPLY_LANG_ID_DETECTAION_FAILURE(113),
                MODEL_NOT_REGISTERED(114),
                MODEL_TYPE_MISUSE(115),
                MODEL_HASH_MISMATCH(116),
                OPTIONAL_MODULE_NOT_AVAILABLE(201),
                OPTIONAL_MODULE_INIT_ERROR(202),
                OPTIONAL_MODULE_INFERENCE_ERROR(203),
                OPTIONAL_MODULE_RELEASE_ERROR(204),
                OPTIONAL_TFLITE_MODULE_INIT_ERROR(205),
                NATIVE_LIBRARY_LOAD_ERROR(206),
                OPTIONAL_MODULE_CREATE_ERROR(207),
                CAMERAX_SOURCE_ERROR(301),
                CAMERA1_SOURCE_CANT_START_ERROR(302),
                CAMERA1_SOURCE_NO_SUITABLE_SIZE_ERROR(303),
                CAMERA1_SOURCE_NO_SUITABLE_FPS_ERROR(304),
                CAMERA1_SOURCE_NO_BYTE_SOURCE_FOUND_ERROR(305),
                CODE_SCANNER_UNAVAILABLE(400),
                CODE_SCANNER_CANCELLED(401),
                CODE_SCANNER_CAMERA_PERMISSION_NOT_GRANTED(402),
                CODE_SCANNER_APP_NAME_UNAVAILABLE(403),
                CODE_SCANNER_TASK_IN_PROGRESS(404),
                CODE_SCANNER_PIPELINE_INITIALIZATION_ERROR(405),
                CODE_SCANNER_PIPELINE_INFERENCE_ERROR(406),
                CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(407),
                LOW_LIGHT_AUTO_EXPOSURE_COMPUTATION_FAILURE(500),
                LOW_LIGHT_IMAGE_CAPTURE_PROCESSING_FAILURE(GenAiException.ErrorCode.NOT_ENOUGH_DISK_SPACE),
                PERMISSION_DENIED(600),
                CANCELLED(601),
                GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(602),
                LOW_MEMORY(603),
                SAPI_BUSY(700),
                SAPI_CANCELLED(701),
                SAPI_NEEDS_SYSTEM_UPDATE(702),
                SAPI_NOT_AVAILABLE(703),
                SAPI_NOT_ENOUGH_DISK_SPACE(704),
                SAPI_REQUEST_PROCESSING_ERROR(705),
                SAPI_REQUEST_TOO_LARGE(706),
                SAPI_RESPONSE_GENERATION_ERROR(707),
                SAPI_RESPONSE_PROCESSING_ERROR(708),
                SAPI_REQUEST_TOO_SMALL(709),
                SAPI_BAD_DATA(710),
                SAPI_BAD_REQUEST(711),
                SAPI_COMPUTE_ERROR(712),
                SAPI_IPC_ERROR(713),
                SAPI_SERVICE_PROCESSING_ERROR(714),
                SAPI_SUSPENDED(715),
                SAPI_INTERNAL_ERROR(716),
                SAPI_NOT_SUPPORTED(717),
                SAPI_SUSPENDED_STATELESS(718),
                SAPI_INTERNAL_ERROR_DOUBLE_MODEL_LOAD_ATTEMPT(719),
                SAPI_BINDING_FAILURE(720),
                SAPI_SERVICE_DISCONNECTED(721),
                SAPI_BINDING_DIED(722),
                SAPI_NULL_BINDING(723),
                SAPI_FEATURE_NOT_FOUND(724),
                SAPI_APK_SERVING_GROUP_MISMATCH(725),
                SAPI_AICORE_INCOMPATIBLE(726),
                SAPI_INVALID_INPUT_IMAGE(727),
                SAPI_PER_APP_BATTERY_USE_QUOTA_EXCEEDED(728),
                SAPI_PER_DEVICE_BATTERY_USE_QUOTA_EXCEEDED(729),
                SAPI_BACKGROUND_USE_BLOCKED(730),
                UNKNOWN_ERROR(9999);

                private final int zzaI;

                zzxp(int i) {
/* 4 */             this.zzaI = i;
                }

                @Override
                public final int zza() {
/* 1 */             return this.zzaI;
                }
            }
