            package com.k2fsa.sherpa.onnx;

            import com.google.ai.edge.gallery.BuildConfig;
            import com.google.mlkit.vision.common.InputImage;
            import com.google.mlkit.vision.pose.PoseLandmark;
            import kotlin.Metadata;
            
            @Metadata(d1 = {"\u0000\u000e\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\b\n\u0000\u001a\u0010\u0010\u0000\u001a\u0004\u0018\u00010\u00012\u0006\u0010\u0002\u001a\u00020\u0003¨\u0006\u0004"}, d2 = {"getOfflineModelConfig", "Lcom/k2fsa/sherpa/onnx/OfflineModelConfig;", "type", "", "sherpa_onnx_release"}, m18k = 2, mv = {1, 7, 1}, xi = 48)
            public final class OfflineRecognizerKt {
                public static final OfflineModelConfig getOfflineModelConfig(int i) {
                    switch (i) {
                        case 0:
/* 6112 */                  return new OfflineModelConfig(null, new OfflineParaformerModelConfig("sherpa-onnx-paraformer-zh-2023-09-14/model.int8.onnx", null, 2, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "paraformer", "sherpa-onnx-paraformer-zh-2023-09-14/tokens.txt", null, null, 27262973, null);
                        case 1:
/* 6056 */                  return new OfflineModelConfig(new OfflineTransducerModelConfig("icefall-asr-multidataset-pruned_transducer_stateless7-2023-05-04/encoder-epoch-30-avg-4.int8.onnx", "icefall-asr-multidataset-pruned_transducer_stateless7-2023-05-04/decoder-epoch-30-avg-4.onnx", "icefall-asr-multidataset-pruned_transducer_stateless7-2023-05-04/joiner-epoch-30-avg-4.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "transducer", "icefall-asr-multidataset-pruned_transducer_stateless7-2023-05-04/tokens.txt", null, null, 27262974, null);
                        case 2:
/* 5997 */                  return new OfflineModelConfig(null, null, new OfflineWhisperModelConfig("sherpa-onnx-whisper-tiny.en/tiny.en-encoder.int8.onnx", "sherpa-onnx-whisper-tiny.en/tiny.en-decoder.int8.onnx", null, null, 0, false, false, 124, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "whisper", "sherpa-onnx-whisper-tiny.en/tiny.en-tokens.txt", null, null, 27262971, null);
                        case 3:
/* 5933 */                  return new OfflineModelConfig(null, null, new OfflineWhisperModelConfig("sherpa-onnx-whisper-base.en/base.en-encoder.int8.onnx", "sherpa-onnx-whisper-base.en/base.en-decoder.int8.onnx", null, null, 0, false, false, 124, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "whisper", "sherpa-onnx-whisper-base.en/base.en-tokens.txt", null, null, 27262971, null);
                        case 4:
/* 5870 */                  return new OfflineModelConfig(new OfflineTransducerModelConfig("icefall-asr-zipformer-wenetspeech-20230615/encoder-epoch-12-avg-4.int8.onnx", "icefall-asr-zipformer-wenetspeech-20230615/decoder-epoch-12-avg-4.onnx", "icefall-asr-zipformer-wenetspeech-20230615/joiner-epoch-12-avg-4.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "transducer", "icefall-asr-zipformer-wenetspeech-20230615/tokens.txt", null, null, 27262974, null);
                        case 5:
/* 5814 */                  return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-zipformer-multi-zh-hans-2023-9-2/encoder-epoch-20-avg-1.int8.onnx", "sherpa-onnx-zipformer-multi-zh-hans-2023-9-2/decoder-epoch-20-avg-1.onnx", "sherpa-onnx-zipformer-multi-zh-hans-2023-9-2/joiner-epoch-20-avg-1.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "transducer", "sherpa-onnx-zipformer-multi-zh-hans-2023-9-2/tokens.txt", null, null, 27262974, null);
                        case 6:
/* 5742 */                  return new OfflineModelConfig(null, null, null, null, null, new OfflineNemoEncDecCtcModelConfig("sherpa-onnx-nemo-ctc-en-citrinet-512/model.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-nemo-ctc-en-citrinet-512/tokens.txt", null, null, 29360095, null);
                        case 7:
/* 5674 */                  return new OfflineModelConfig(null, null, null, null, null, new OfflineNemoEncDecCtcModelConfig("sherpa-onnx-nemo-fast-conformer-ctc-be-de-en-es-fr-hr-it-pl-ru-uk-20k/model.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-nemo-fast-conformer-ctc-be-de-en-es-fr-hr-it-pl-ru-uk-20k/tokens.txt", null, null, 29360095, null);
                        case 8:
/* 5606 */                  return new OfflineModelConfig(null, null, null, null, null, new OfflineNemoEncDecCtcModelConfig("sherpa-onnx-nemo-fast-conformer-ctc-en-24500/model.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-nemo-fast-conformer-ctc-en-24500/tokens.txt", null, null, 29360095, null);
                        case 9:
/* 5538 */                  return new OfflineModelConfig(null, null, null, null, null, new OfflineNemoEncDecCtcModelConfig("sherpa-onnx-nemo-fast-conformer-ctc-en-de-es-fr-14288/model.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-nemo-fast-conformer-ctc-en-de-es-fr-14288/tokens.txt", null, null, 29360095, null);
                        case 10:
/* 5470 */                  return new OfflineModelConfig(null, null, null, null, null, new OfflineNemoEncDecCtcModelConfig("sherpa-onnx-nemo-fast-conformer-ctc-es-1424/model.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-nemo-fast-conformer-ctc-es-1424/tokens.txt", null, null, 29360095, null);
                        case 11:
/* 5402 */                  return new OfflineModelConfig(null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "sherpa-onnx-telespeech-ctc-int8-zh-2024-06-04/model.int8.onnx", 0, false, null, "telespeech_ctc", "sherpa-onnx-telespeech-ctc-int8-zh-2024-06-04/tokens.txt", null, null, 27131903, null);
                        case 12:
/* 5341 */                  return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-zipformer-thai-2024-06-20/encoder-epoch-12-avg-5.int8.onnx", "sherpa-onnx-zipformer-thai-2024-06-20/decoder-epoch-12-avg-5.onnx", "sherpa-onnx-zipformer-thai-2024-06-20/joiner-epoch-12-avg-5.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "transducer", "sherpa-onnx-zipformer-thai-2024-06-20/tokens.txt", null, null, 27262974, null);
                        case 13:
/* 5269 */                  return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-zipformer-korean-2024-06-24/encoder-epoch-99-avg-1.int8.onnx", "sherpa-onnx-zipformer-korean-2024-06-24/decoder-epoch-99-avg-1.onnx", "sherpa-onnx-zipformer-korean-2024-06-24/joiner-epoch-99-avg-1.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "transducer", "sherpa-onnx-zipformer-korean-2024-06-24/tokens.txt", null, null, 27262974, null);
                        case 14:
/* 5197 */                  return new OfflineModelConfig(null, new OfflineParaformerModelConfig("sherpa-onnx-paraformer-zh-small-2024-03-09/model.int8.onnx", null, 2, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "paraformer", "sherpa-onnx-paraformer-zh-small-2024-03-09/tokens.txt", null, null, 27262973, null);
                        case 15:
/* 5129 */                  return new OfflineModelConfig(null, null, null, null, null, null, new OfflineSenseVoiceModelConfig("sherpa-onnx-sense-voice-zh-en-ja-ko-yue-int8-2024-07-17/model.int8.onnx", null, false, null, 14, null), null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-sense-voice-zh-en-ja-ko-yue-int8-2024-07-17/tokens.txt", null, null, 29360063, null);
                        case 16:
/* 5055 */                  return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-zipformer-ja-reazonspeech-2024-08-01/encoder-epoch-99-avg-1.int8.onnx", "sherpa-onnx-zipformer-ja-reazonspeech-2024-08-01/decoder-epoch-99-avg-1.onnx", "sherpa-onnx-zipformer-ja-reazonspeech-2024-08-01/joiner-epoch-99-avg-1.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "transducer", "sherpa-onnx-zipformer-ja-reazonspeech-2024-08-01/tokens.txt", null, null, 27262974, null);
                        case 17:
/* 4983 */                  return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-zipformer-ru-2024-09-18/encoder.int8.onnx", "sherpa-onnx-zipformer-ru-2024-09-18/decoder.onnx", "sherpa-onnx-zipformer-ru-2024-09-18/joiner.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "transducer", "sherpa-onnx-zipformer-ru-2024-09-18/tokens.txt", null, null, 27262974, null);
                        case PoseLandmark.RIGHT_PINKY:
/* 4911 */                  return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-small-zipformer-ru-2024-09-18/encoder.int8.onnx", "sherpa-onnx-small-zipformer-ru-2024-09-18/decoder.onnx", "sherpa-onnx-small-zipformer-ru-2024-09-18/joiner.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "transducer", "sherpa-onnx-small-zipformer-ru-2024-09-18/tokens.txt", null, null, 27262974, null);
                        case PoseLandmark.LEFT_INDEX:
/* 4839 */                  return new OfflineModelConfig(null, null, null, null, null, new OfflineNemoEncDecCtcModelConfig("sherpa-onnx-nemo-ctc-giga-am-russian-2024-10-24/model.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-nemo-ctc-giga-am-russian-2024-10-24/tokens.txt", null, null, 29360095, null);
                        case PoseLandmark.RIGHT_INDEX:
/* 4772 */                  return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-nemo-transducer-giga-am-russian-2024-10-24/encoder.int8.onnx", "sherpa-onnx-nemo-transducer-giga-am-russian-2024-10-24/decoder.onnx", "sherpa-onnx-nemo-transducer-giga-am-russian-2024-10-24/joiner.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "nemo_transducer", "sherpa-onnx-nemo-transducer-giga-am-russian-2024-10-24/tokens.txt", null, null, 27262974, null);
                        case PoseLandmark.LEFT_THUMB:
/* 4703 */                  return new OfflineModelConfig(null, null, null, null, new OfflineMoonshineModelConfig("sherpa-onnx-moonshine-tiny-en-int8/preprocess.onnx", "sherpa-onnx-moonshine-tiny-en-int8/encode.int8.onnx", "sherpa-onnx-moonshine-tiny-en-int8/uncached_decode.int8.onnx", "sherpa-onnx-moonshine-tiny-en-int8/cached_decode.int8.onnx", null, 16, null), null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-moonshine-tiny-en-int8/tokens.txt", null, null, 29360111, null);
                        case PoseLandmark.RIGHT_THUMB:
/* 4628 */                  return new OfflineModelConfig(null, null, null, null, new OfflineMoonshineModelConfig("sherpa-onnx-moonshine-base-en-int8/preprocess.onnx", "sherpa-onnx-moonshine-base-en-int8/encode.int8.onnx", "sherpa-onnx-moonshine-base-en-int8/uncached_decode.int8.onnx", "sherpa-onnx-moonshine-base-en-int8/cached_decode.int8.onnx", null, 16, null), null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-moonshine-base-en-int8/tokens.txt", null, null, 29360111, null);
                        case PoseLandmark.LEFT_HIP:
/* 4554 */                  return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-zipformer-zh-en-2023-11-22/encoder-epoch-34-avg-19.int8.onnx", "sherpa-onnx-zipformer-zh-en-2023-11-22/decoder-epoch-34-avg-19.onnx", "sherpa-onnx-zipformer-zh-en-2023-11-22/joiner-epoch-34-avg-19.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "transducer", "sherpa-onnx-zipformer-zh-en-2023-11-22/tokens.txt", null, null, 27262974, null);
                        case PoseLandmark.RIGHT_HIP:
/* 4488 */                  return new OfflineModelConfig(null, null, null, new OfflineFireRedAsrModelConfig("sherpa-onnx-fire-red-asr-large-zh_en-2025-02-16/encoder.int8.onnx", "sherpa-onnx-fire-red-asr-large-zh_en-2025-02-16/decoder.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-fire-red-asr-large-zh_en-2025-02-16/tokens.txt", null, null, 29360119, null);
                        case PoseLandmark.LEFT_KNEE:
/* 4425 */                  return new OfflineModelConfig(null, null, null, null, null, null, null, new OfflineDolphinModelConfig("sherpa-onnx-dolphin-base-ctc-multi-lang-int8-2025-04-02/model.int8.onnx"), null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-dolphin-base-ctc-multi-lang-int8-2025-04-02/tokens.txt", null, null, 29359999, null);
                        case PoseLandmark.RIGHT_KNEE:
/* 4364 */                  return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-zipformer-vi-int8-2025-04-20/encoder-epoch-12-avg-8.int8.onnx", "sherpa-onnx-zipformer-vi-int8-2025-04-20/decoder-epoch-12-avg-8.onnx", "sherpa-onnx-zipformer-vi-int8-2025-04-20/joiner-epoch-12-avg-8.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "transducer", "sherpa-onnx-zipformer-vi-int8-2025-04-20/tokens.txt", null, null, 27262974, null);
                        case 27:
/* 4301 */                  return new OfflineModelConfig(null, null, null, null, null, new OfflineNemoEncDecCtcModelConfig("sherpa-onnx-nemo-ctc-giga-am-v2-russian-2025-04-19/model.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-nemo-ctc-giga-am-v2-russian-2025-04-19/tokens.txt", null, null, 29360095, null);
                        case PoseLandmark.RIGHT_ANKLE:
/* 4243 */                  return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-nemo-transducer-giga-am-v2-russian-2025-04-19/encoder.int8.onnx", "sherpa-onnx-nemo-transducer-giga-am-v2-russian-2025-04-19/decoder.onnx", "sherpa-onnx-nemo-transducer-giga-am-v2-russian-2025-04-19/joiner.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "nemo_transducer", "sherpa-onnx-nemo-transducer-giga-am-v2-russian-2025-04-19/tokens.txt", null, null, 27262974, null);
                        case PoseLandmark.LEFT_HEEL:
/* 4182 */                  return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-zipformer-ru-int8-2025-04-20/encoder.int8.onnx", "sherpa-onnx-zipformer-ru-int8-2025-04-20/decoder.onnx", "sherpa-onnx-zipformer-ru-int8-2025-04-20/joiner.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "transducer", "sherpa-onnx-zipformer-ru-int8-2025-04-20/tokens.txt", null, null, 27262974, null);
                        case 30:
/* 4122 */                  return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-nemo-parakeet-tdt-0.6b-v2-int8/encoder.int8.onnx", "sherpa-onnx-nemo-parakeet-tdt-0.6b-v2-int8/decoder.int8.onnx", "sherpa-onnx-nemo-parakeet-tdt-0.6b-v2-int8/joiner.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "nemo_transducer", "sherpa-onnx-nemo-parakeet-tdt-0.6b-v2-int8/tokens.txt", null, null, 27262974, null);
                        case PoseLandmark.LEFT_FOOT_INDEX:
/* 4063 */                  return new OfflineModelConfig(null, null, null, null, null, null, null, null, new OfflineZipformerCtcModelConfig("sherpa-onnx-zipformer-ctc-zh-int8-2025-07-03/model.int8.onnx", null, 2, null), null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-zipformer-ctc-zh-int8-2025-07-03/tokens.txt", null, null, 29359871, null);
                        case 32:
/* 4009 */                  return new OfflineModelConfig(null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, new OfflineCanaryModelConfig("sherpa-onnx-nemo-canary-180m-flash-en-es-de-fr-int8/encoder.int8.onnx", "sherpa-onnx-nemo-canary-180m-flash-en-es-de-fr-int8/decoder.int8.onnx", "en", "en", true), null, null, 0, false, null, null, "sherpa-onnx-nemo-canary-180m-flash-en-es-de-fr-int8/tokens.txt", null, null, 29327359, null);
                        case 33:
/* 3948 */                  return new OfflineModelConfig(null, null, null, null, null, new OfflineNemoEncDecCtcModelConfig("sherpa-onnx-nemo-parakeet_tdt_ctc_110m-en-36000-int8/model.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-nemo-parakeet_tdt_ctc_110m-en-36000-int8/tokens.txt", null, null, 29360095, null);
                        case 34:
/* 3896 */                  return new OfflineModelConfig(null, null, null, null, null, new OfflineNemoEncDecCtcModelConfig("sherpa-onnx-nemo-parakeet-tdt_ctc-0.6b-ja-35000-int8/model.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-nemo-parakeet-tdt_ctc-0.6b-ja-35000-int8/tokens.txt", null, null, 29360095, null);
                        case InputImage.IMAGE_FORMAT_YUV_420_888:
/* 3828 */                  return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-nemo-transducer-stt_pt_fastconformer_hybrid_large_pc-int8/encoder.int8.onnx", "sherpa-onnx-nemo-transducer-stt_pt_fastconformer_hybrid_large_pc-int8/decoder.int8.onnx", "sherpa-onnx-nemo-transducer-stt_pt_fastconformer_hybrid_large_pc-int8/joiner.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "nemo_transducer", "sherpa-onnx-nemo-transducer-stt_pt_fastconformer_hybrid_large_pc-int8/tokens.txt", null, null, 27262974, null);
                        case 36:
/* 3756 */                  return new OfflineModelConfig(null, null, null, null, null, new OfflineNemoEncDecCtcModelConfig("sherpa-onnx-nemo-stt_pt_fastconformer_hybrid_large_pc-int8/model.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-nemo-stt_pt_fastconformer_hybrid_large_pc-int8/tokens.txt", null, null, 29360095, null);
                        case 37:
/* 3688 */                  return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-nemo-transducer-stt_de_fastconformer_hybrid_large_pc-int8/encoder.int8.onnx", "sherpa-onnx-nemo-transducer-stt_de_fastconformer_hybrid_large_pc-int8/decoder.int8.onnx", "sherpa-onnx-nemo-transducer-stt_de_fastconformer_hybrid_large_pc-int8/joiner.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "nemo_transducer", "sherpa-onnx-nemo-transducer-stt_de_fastconformer_hybrid_large_pc-int8/tokens.txt", null, null, 27262974, null);
                        case 38:
/* 3616 */                  return new OfflineModelConfig(null, null, null, null, null, new OfflineNemoEncDecCtcModelConfig("sherpa-onnx-nemo-stt_de_fastconformer_hybrid_large_pc-int8/model.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-nemo-stt_de_fastconformer_hybrid_large_pc-int8/tokens.txt", null, null, 29360095, null);
                        case 39:
/* 3548 */                  return new OfflineModelConfig(null, null, null, null, null, null, null, null, new OfflineZipformerCtcModelConfig("sherpa-onnx-zipformer-ctc-small-zh-int8-2025-07-16/model.int8.onnx", null, 2, null), null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-zipformer-ctc-small-zh-int8-2025-07-16/tokens.txt", null, null, 29359871, null);
                        case 40:
/* 3480 */                  return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-nemo-parakeet-tdt-0.6b-v3-int8/encoder.int8.onnx", "sherpa-onnx-nemo-parakeet-tdt-0.6b-v3-int8/decoder.int8.onnx", "sherpa-onnx-nemo-parakeet-tdt-0.6b-v3-int8/joiner.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "nemo_transducer", "sherpa-onnx-nemo-parakeet-tdt-0.6b-v3-int8/tokens.txt", null, null, 27262974, null);
                        case 41:
/* 3408 */                  return new OfflineModelConfig(null, null, null, null, null, null, new OfflineSenseVoiceModelConfig("sherpa-onnx-sense-voice-zh-en-ja-ko-yue-int8-2025-09-09/model.int8.onnx", null, false, null, 14, null), null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-sense-voice-zh-en-ja-ko-yue-int8-2025-09-09/tokens.txt", null, null, 29360063, null);
                        case 42:
/* 3334 */                  return new OfflineModelConfig(null, null, null, null, null, null, null, null, null, new OfflineWenetCtcModelConfig("sherpa-onnx-wenetspeech-yue-u2pp-conformer-ctc-zh-en-cantonese-int8-2025-09-10/model.int8.onnx"), null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-wenetspeech-yue-u2pp-conformer-ctc-zh-en-cantonese-int8-2025-09-10/tokens.txt", null, null, 29359615, null);
                        case 43:
/* 3266 */                  return new OfflineModelConfig(null, new OfflineParaformerModelConfig("sherpa-onnx-paraformer-zh-int8-2025-10-07/model.int8.onnx", null, 2, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "paraformer", "sherpa-onnx-paraformer-zh-int8-2025-10-07/tokens.txt", null, null, 27262973, null);
                        case 44:
/* 3198 */                  return new OfflineModelConfig(null, null, null, null, null, null, null, null, null, null, new OfflineOmnilingualAsrCtcModelConfig("sherpa-onnx-omnilingual-asr-1600-languages-300M-ctc-int8-2025-11-12/model.int8.onnx"), null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-omnilingual-asr-1600-languages-300M-ctc-int8-2025-11-12/tokens.txt", null, null, 29359103, null);
                        case BuildConfig.VERSION_CODE:
/* 3130 */                  return new OfflineModelConfig(null, null, null, null, null, null, null, null, null, null, null, new OfflineMedAsrCtcModelConfig("sherpa-onnx-medasr-ctc-en-int8-2025-12-25/model.int8.onnx"), null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-medasr-ctc-en-int8-2025-12-25/tokens.txt", null, null, 29358079, null);
                        case 46:
/* 3062 */                  return new OfflineModelConfig(null, null, null, null, null, null, null, null, null, null, null, null, new OfflineFunAsrNanoModelConfig("sherpa-onnx-funasr-nano-int8-2025-12-30/encoder_adaptor.int8.onnx", "sherpa-onnx-funasr-nano-int8-2025-12-30/llm.int8.onnx", "sherpa-onnx-funasr-nano-int8-2025-12-30/embedding.int8.onnx", "sherpa-onnx-funasr-nano-int8-2025-12-30/Qwen3-0.6B", null, null, 0, 0.0f, 0.0f, 0, null, false, null, 8176, null), null, null, null, null, null, 3, false, null, null, "", null, null, 29093887, null);
                        case 47:
/* 2972 */                  return new OfflineModelConfig(null, null, null, null, null, null, null, null, null, new OfflineWenetCtcModelConfig("sherpa-onnx-wenetspeech-wu-u2pp-conformer-ctc-zh-int8-2026-02-03/model.int8.onnx"), null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-wenetspeech-wu-u2pp-conformer-ctc-zh-int8-2026-02-03/tokens.txt", null, null, 29359615, null);
                        case 48:
/* 2904 */                  return new OfflineModelConfig(null, null, null, null, null, null, null, null, null, new OfflineWenetCtcModelConfig("sherpa-onnx-wenetspeech-wu-u2pp-conformer-ctc-zh-2026-02-03/model.onnx"), null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-wenetspeech-wu-u2pp-conformer-ctc-zh-2026-02-03/tokens.txt", null, null, 29359615, null);
                        case 49:
/* 2837 */                  return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-zipformer-vi-30M-int8-2026-02-09/encoder.int8.onnx", "sherpa-onnx-zipformer-vi-30M-int8-2026-02-09/decoder.onnx", "sherpa-onnx-zipformer-vi-30M-int8-2026-02-09/joiner.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "transducer", "sherpa-onnx-zipformer-vi-30M-int8-2026-02-09/tokens.txt", null, null, 27262974, null);
                        case 50:
/* 2768 */                  return new OfflineModelConfig(null, null, null, null, null, null, null, null, null, null, null, null, null, null, new OfflineFireRedAsrCtcModelConfig("sherpa-onnx-fire-red-asr2-ctc-zh_en-int8-2026-02-25/model.int8.onnx"), null, null, null, 0, false, null, null, "sherpa-onnx-fire-red-asr2-ctc-zh_en-int8-2026-02-25/tokens.txt", null, null, 29343743, null);
                        case 51:
/* 2703 */                  return new OfflineModelConfig(null, null, null, null, new OfflineMoonshineModelConfig(null, "sherpa-onnx-moonshine-tiny-ko-quantized-2026-02-27/encoder_model.ort", null, null, "sherpa-onnx-moonshine-tiny-ko-quantized-2026-02-27/decoder_model_merged.ort", 13, null), null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-moonshine-tiny-ko-quantized-2026-02-27/tokens.txt", null, null, 29360111, null);
                        case 52:
/* 2631 */                  return new OfflineModelConfig(null, null, null, null, new OfflineMoonshineModelConfig(null, "sherpa-onnx-moonshine-tiny-ja-quantized-2026-02-27/encoder_model.ort", null, null, "sherpa-onnx-moonshine-tiny-ja-quantized-2026-02-27/decoder_model_merged.ort", 13, null), null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-moonshine-tiny-ja-quantized-2026-02-27/tokens.txt", null, null, 29360111, null);
                        case 53:
/* 2560 */                  return new OfflineModelConfig(null, null, null, null, new OfflineMoonshineModelConfig(null, "sherpa-onnx-moonshine-tiny-en-quantized-2026-02-27/encoder_model.ort", null, null, "sherpa-onnx-moonshine-tiny-en-quantized-2026-02-27/decoder_model_merged.ort", 13, null), null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-moonshine-tiny-en-quantized-2026-02-27/tokens.txt", null, null, 29360111, null);
                        case 54:
/* 2490 */                  return new OfflineModelConfig(null, null, null, null, new OfflineMoonshineModelConfig(null, "sherpa-onnx-moonshine-base-zh-quantized-2026-02-27/encoder_model.ort", null, null, "sherpa-onnx-moonshine-base-zh-quantized-2026-02-27/decoder_model_merged.ort", 13, null), null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-moonshine-base-zh-quantized-2026-02-27/tokens.txt", null, null, 29360111, null);
                        case 55:
/* 2421 */                  return new OfflineModelConfig(null, null, null, null, new OfflineMoonshineModelConfig(null, "sherpa-onnx-moonshine-base-vi-quantized-2026-02-27/encoder_model.ort", null, null, "sherpa-onnx-moonshine-base-vi-quantized-2026-02-27/decoder_model_merged.ort", 13, null), null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-moonshine-base-vi-quantized-2026-02-27/tokens.txt", null, null, 29360111, null);
                        case 56:
/* 2356 */                  return new OfflineModelConfig(null, null, null, null, new OfflineMoonshineModelConfig(null, "sherpa-onnx-moonshine-base-uk-quantized-2026-02-27/encoder_model.ort", null, null, "sherpa-onnx-moonshine-base-uk-quantized-2026-02-27/decoder_model_merged.ort", 13, null), null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-moonshine-base-uk-quantized-2026-02-27/tokens.txt", null, null, 29360111, null);
                        case 57:
/* 2292 */                  return new OfflineModelConfig(null, null, null, null, new OfflineMoonshineModelConfig(null, "sherpa-onnx-moonshine-base-ja-quantized-2026-02-27/encoder_model.ort", null, null, "sherpa-onnx-moonshine-base-ja-quantized-2026-02-27/decoder_model_merged.ort", 13, null), null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-moonshine-base-ja-quantized-2026-02-27/tokens.txt", null, null, 29360111, null);
                        case 58:
/* 2229 */                  return new OfflineModelConfig(null, null, null, null, new OfflineMoonshineModelConfig(null, "sherpa-onnx-moonshine-base-es-quantized-2026-02-27/encoder_model.ort", null, null, "sherpa-onnx-moonshine-base-es-quantized-2026-02-27/decoder_model_merged.ort", 13, null), null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-moonshine-base-es-quantized-2026-02-27/tokens.txt", null, null, 29360111, null);
                        case 59:
/* 2167 */                  return new OfflineModelConfig(null, null, null, null, new OfflineMoonshineModelConfig(null, "sherpa-onnx-moonshine-base-en-quantized-2026-02-27/encoder_model.ort", null, null, "sherpa-onnx-moonshine-base-en-quantized-2026-02-27/decoder_model_merged.ort", 13, null), null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-moonshine-base-en-quantized-2026-02-27/tokens.txt", null, null, 29360111, null);
                        case 60:
/* 2106 */                  return new OfflineModelConfig(null, null, null, null, new OfflineMoonshineModelConfig(null, "sherpa-onnx-moonshine-base-ar-quantized-2026-02-27/encoder_model.ort", null, null, "sherpa-onnx-moonshine-base-ar-quantized-2026-02-27/decoder_model_merged.ort", 13, null), null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-moonshine-base-ar-quantized-2026-02-27/tokens.txt", null, null, 29360111, null);
                        case 61:
/* 2046 */                  return new OfflineModelConfig(null, null, null, null, null, null, null, null, null, null, null, null, null, new OfflineQwen3AsrModelConfig("sherpa-onnx-qwen3-asr-0.6B-int8-2026-03-25/conv_frontend.onnx", "sherpa-onnx-qwen3-asr-0.6B-int8-2026-03-25/encoder.int8.onnx", "sherpa-onnx-qwen3-asr-0.6B-int8-2026-03-25/decoder.int8.onnx", "sherpa-onnx-qwen3-asr-0.6B-int8-2026-03-25/tokenizer", 0, 0, 0.0f, 0.0f, 0, null, 1008, null), null, null, null, null, 3, false, null, null, "", null, null, 29089791, null);
                        case 62:
/* 1979 */                  return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-nemo-parakeet-unified-en-0.6b-int8-non-streaming/encoder.int8.onnx", "sherpa-onnx-nemo-parakeet-unified-en-0.6b-int8-non-streaming/decoder.int8.onnx", "sherpa-onnx-nemo-parakeet-unified-en-0.6b-int8-non-streaming/joiner.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "nemo_transducer", "sherpa-onnx-nemo-parakeet-unified-en-0.6b-int8-non-streaming/tokens.txt", null, null, 27262974, null);
                        default:
                            switch (i) {
                                case 9000:
/* 1923 */                          return new OfflineModelConfig(null, null, null, null, null, null, new OfflineSenseVoiceModelConfig("sherpa-onnx-qnn-5-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/libmodel.so", null, false, new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-5-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/model.bin", "libQnnSystem.so"), 6, null), null, null, null, null, null, null, null, null, null, null, null, 0, true, "qnn", null, "sherpa-onnx-qnn-5-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/tokens.txt", null, null, 27787199, null);
                                case 9001:
/* 1844 */                          return new OfflineModelConfig(null, null, null, null, null, null, new OfflineSenseVoiceModelConfig("sherpa-onnx-qnn-8-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/libmodel.so", null, false, new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-8-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/model.bin", "libQnnSystem.so"), 6, null), null, null, null, null, null, null, null, null, null, null, null, 0, true, "qnn", null, "sherpa-onnx-qnn-8-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/tokens.txt", null, null, 27787199, null);
                                case 9002:
/* 1765 */                          return new OfflineModelConfig(null, null, null, null, null, null, new OfflineSenseVoiceModelConfig("sherpa-onnx-qnn-10-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/libmodel.so", null, false, new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-10-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/model.bin", "libQnnSystem.so"), 6, null), null, null, null, null, null, null, null, null, null, null, null, 0, true, "qnn", null, "sherpa-onnx-qnn-10-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/tokens.txt", null, null, 27787199, null);
                                case 9003:
/* 1686 */                          return new OfflineModelConfig(null, null, null, null, null, null, new OfflineSenseVoiceModelConfig("sherpa-onnx-qnn-13-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/libmodel.so", null, false, new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-13-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/model.bin", "libQnnSystem.so"), 6, null), null, null, null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-13-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/tokens.txt", null, null, 28311487, null);
                                case 9004:
/* 1607 */                          return new OfflineModelConfig(null, null, null, null, null, null, new OfflineSenseVoiceModelConfig("sherpa-onnx-qnn-15-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/libmodel.so", null, false, new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-15-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/model.bin", "libQnnSystem.so"), 6, null), null, null, null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-15-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/tokens.txt", null, null, 28311487, null);
                                case 9005:
/* 1528 */                          return new OfflineModelConfig(null, null, null, null, null, null, new OfflineSenseVoiceModelConfig("sherpa-onnx-qnn-18-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/libmodel.so", null, false, new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-18-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/model.bin", "libQnnSystem.so"), 6, null), null, null, null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-18-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/tokens.txt", null, null, 28311487, null);
                                case 9006:
/* 1449 */                          return new OfflineModelConfig(null, null, null, null, null, null, new OfflineSenseVoiceModelConfig("sherpa-onnx-qnn-20-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/libmodel.so", null, false, new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-20-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/model.bin", "libQnnSystem.so"), 6, null), null, null, null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-20-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/tokens.txt", null, null, 28311487, null);
                                case 9007:
/* 1370 */                          return new OfflineModelConfig(null, null, null, null, null, null, new OfflineSenseVoiceModelConfig("sherpa-onnx-qnn-23-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/libmodel.so", null, false, new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-23-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/model.bin", "libQnnSystem.so"), 6, null), null, null, null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-23-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/tokens.txt", null, null, 28311487, null);
                                case 9008:
/* 1291 */                          return new OfflineModelConfig(null, null, null, null, null, null, new OfflineSenseVoiceModelConfig("sherpa-onnx-qnn-25-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/libmodel.so", null, false, new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-25-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/model.bin", "libQnnSystem.so"), 6, null), null, null, null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-25-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/tokens.txt", null, null, 28311487, null);
                                case 9009:
/* 1212 */                          return new OfflineModelConfig(null, null, null, null, null, null, new OfflineSenseVoiceModelConfig("sherpa-onnx-qnn-28-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/libmodel.so", null, false, new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-28-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/model.bin", "libQnnSystem.so"), 6, null), null, null, null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-28-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/tokens.txt", null, null, 28311487, null);
                                case 9010:
/* 1133 */                          return new OfflineModelConfig(null, null, null, null, null, null, new OfflineSenseVoiceModelConfig("sherpa-onnx-qnn-30-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/libmodel.so", null, false, new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-30-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/model.bin", "libQnnSystem.so"), 6, null), null, null, null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-30-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/tokens.txt", null, null, 28311487, null);
                                case 9011:
/* 1054 */                          return new OfflineModelConfig(null, null, null, null, null, null, null, null, new OfflineZipformerCtcModelConfig("sherpa-onnx-qnn-5-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/libmodel.so", new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-5-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/model.bin", "libQnnSystem.so")), null, null, null, null, null, null, null, null, null, 0, true, "qnn", null, "sherpa-onnx-qnn-5-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/tokens.txt", null, null, 27787007, null);
                                case 9012:
/* 979 */                           return new OfflineModelConfig(null, null, null, null, null, null, null, null, new OfflineZipformerCtcModelConfig("sherpa-onnx-qnn-8-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/libmodel.so", new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-8-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/model.bin", "libQnnSystem.so")), null, null, null, null, null, null, null, null, null, 0, true, "qnn", null, "sherpa-onnx-qnn-8-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/tokens.txt", null, null, 27787007, null);
                                case 9013:
/* 904 */                           return new OfflineModelConfig(null, null, null, null, null, null, null, null, new OfflineZipformerCtcModelConfig("sherpa-onnx-qnn-10-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/libmodel.so", new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-10-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/model.bin", "libQnnSystem.so")), null, null, null, null, null, null, null, null, null, 0, true, "qnn", null, "sherpa-onnx-qnn-10-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/tokens.txt", null, null, 27787007, null);
                                case 9014:
/* 829 */                           return new OfflineModelConfig(null, null, null, null, null, null, null, null, new OfflineZipformerCtcModelConfig("sherpa-onnx-qnn-13-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/libmodel.so", new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-13-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/model.bin", "libQnnSystem.so")), null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-13-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/tokens.txt", null, null, 28311295, null);
                                case 9015:
/* 755 */                           return new OfflineModelConfig(null, null, null, null, null, null, null, null, new OfflineZipformerCtcModelConfig("sherpa-onnx-qnn-15-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/libmodel.so", new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-15-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/model.bin", "libQnnSystem.so")), null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-15-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/tokens.txt", null, null, 28311295, null);
                                case 9016:
/* 682 */                           return new OfflineModelConfig(null, null, null, null, null, null, null, null, new OfflineZipformerCtcModelConfig("sherpa-onnx-qnn-18-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/libmodel.so", new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-18-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/model.bin", "libQnnSystem.so")), null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-18-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/tokens.txt", null, null, 28311295, null);
                                case 9017:
/* 610 */                           return new OfflineModelConfig(null, null, null, null, null, null, null, null, new OfflineZipformerCtcModelConfig("sherpa-onnx-qnn-20-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/libmodel.so", new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-20-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/model.bin", "libQnnSystem.so")), null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-20-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/tokens.txt", null, null, 28311295, null);
                                case 9018:
/* 539 */                           return new OfflineModelConfig(null, null, null, null, null, null, null, null, new OfflineZipformerCtcModelConfig("sherpa-onnx-qnn-23-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/libmodel.so", new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-23-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/model.bin", "libQnnSystem.so")), null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-23-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/tokens.txt", null, null, 28311295, null);
                                case 9019:
/* 469 */                           return new OfflineModelConfig(null, null, null, null, null, null, null, null, new OfflineZipformerCtcModelConfig("sherpa-onnx-qnn-25-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/libmodel.so", new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-25-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/model.bin", "libQnnSystem.so")), null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-25-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/tokens.txt", null, null, 28311295, null);
                                case 9020:
/* 400 */                           return new OfflineModelConfig(null, null, null, null, null, null, null, null, new OfflineZipformerCtcModelConfig("sherpa-onnx-qnn-28-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/libmodel.so", new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-28-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/model.bin", "libQnnSystem.so")), null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-28-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/tokens.txt", null, null, 28311295, null);
                                case 9021:
/* 332 */                           return new OfflineModelConfig(null, null, null, null, null, null, null, null, new OfflineZipformerCtcModelConfig("sherpa-onnx-qnn-30-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/libmodel.so", new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-30-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/model.bin", "libQnnSystem.so")), null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-30-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/tokens.txt", null, null, 28311295, null);
                                case 9022:
/* 265 */                           return new OfflineModelConfig(null, null, null, null, null, null, new OfflineSenseVoiceModelConfig(null, null, false, new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-SM8850-binary-10-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8/model.bin", "libQnnSystem.so"), 7, null), null, null, null, null, null, null, null, null, null, null, null, 0, true, "qnn", null, "sherpa-onnx-qnn-SM8850-binary-10-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8/tokens.txt", null, null, 27787199, null);
                                case 9023:
/* 198 */                           return new OfflineModelConfig(null, new OfflineParaformerModelConfig("sherpa-onnx-qnn-5-seconds-paraformer-zh-2023-03-28-int8-android-aarch64/libencoder.so,sherpa-onnx-qnn-5-seconds-paraformer-zh-2023-03-28-int8-android-aarch64/libpredictor.so,sherpa-onnx-qnn-5-seconds-paraformer-zh-2023-03-28-int8-android-aarch64/libdecoder.so", new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-5-seconds-paraformer-zh-2023-03-28-int8-android-aarch64/encoder.bin,sherpa-onnx-qnn-5-seconds-paraformer-zh-2023-03-28-int8-android-aarch64/predictor.bin,sherpa-onnx-qnn-5-seconds-paraformer-zh-2023-03-28-int8-android-aarch64/decoder.bin", "libQnnSystem.so")), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, true, "qnn", null, "sherpa-onnx-qnn-5-seconds-paraformer-zh-2023-03-28-int8-android-aarch64/tokens.txt", null, null, 27787261, null);
                                case 9024:
/* 134 */                           return new OfflineModelConfig(null, new OfflineParaformerModelConfig("sherpa-onnx-qnn-5-seconds-paraformer-zh-2025-10-07-int8-android-aarch64/libencoder.so,sherpa-onnx-qnn-5-seconds-paraformer-zh-2025-10-07-int8-android-aarch64/libpredictor.so,sherpa-onnx-qnn-5-seconds-paraformer-zh-2025-10-07-int8-android-aarch64/libdecoder.so", new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-5-seconds-paraformer-zh-2025-10-07-int8-android-aarch64/encoder.bin,sherpa-onnx-qnn-5-seconds-paraformer-zh-2025-10-07-int8-android-aarch64/predictor.bin,sherpa-onnx-qnn-5-seconds-paraformer-zh-2025-10-07-int8-android-aarch64/decoder.bin", "libQnnSystem.so")), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, true, "qnn", null, "sherpa-onnx-qnn-5-seconds-paraformer-zh-2025-10-07-int8-android-aarch64/tokens.txt", null, null, 27787261, null);
                                case 9025:
/* 71 */                            return new OfflineModelConfig(null, new OfflineParaformerModelConfig(null, new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-SM8850-binary-5-seconds-paraformer-zh-2023-03-28-int8/encoder.bin,sherpa-onnx-qnn-SM8850-binary-5-seconds-paraformer-zh-2023-03-28-int8/predictor.bin,sherpa-onnx-qnn-SM8850-binary-5-seconds-paraformer-zh-2023-03-28-int8/decoder.bin", "libQnnSystem.so"), 1, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, true, "qnn", null, "sherpa-onnx-qnn-SM8850-binary-5-seconds-paraformer-zh-2023-03-28-int8/tokens.txt", null, null, 27787261, null);
                                default:
/* 2 */                             return null;
                            }
                    }
                }
            }
